language: python
python:
  - "3.6"
cache: pip
before_install:
  - export TZ=Europe/Berlin
install:
  - pip install -r requirements.txt
script:
  - pytest
notifications:
  email: true
branches:
  only:
    - master
